spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/builder?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration
server:
  port: 8080
